[[plugins]]
repo = 'cocopon/iceberg.vim'


[[plugins]]
repo = 'tpope/vim-commentary'
hook_add='''
  autocmd FileType mma setlocal commentstring=(*\ %s\ *)
'''

[[plugins]]
repo = 'machakann/vim-highlightedyank'


[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add='''
  set laststatus=2
  set noshowmode
  let g:lightline = {
    \ 'colorscheme' : 'iceberg',
    \ }
'''


[[plugins]]
repo = 'lambdalisue/fern.vim'
hook_add='''
  nnoremap <C-f> :Fern . -reveal=% -drawer -toggle -width=40<CR>
'''

[[plugins]]
repo = 'lambdalisue/fern-git-status.vim'

[[plugins]]
repo = 'lambdalisue/nerdfont.vim'

[[plugins]]
repo = 'lambdalisue/fern-renderer-nerdfont.vim'
hook_add='''
  let g:fern#renderer = 'nerdfont'
'''

[[plugins]]
repo = 'lambdalisue/glyph-palette.vim'
hook_add='''
  augroup my-glyph-palette
  autocmd! *
  autocmd FileType fern call glyph_palette#apply()
  autocmd FileType nerdtree,startify call glyph_palette#apply()
augroup END
'''

[[plugins]]
repo = 'sheerun/vim-polyglot'

[[plugins]]
repo = 'rhysd/vim-grammarous'

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add= '''
  let g:indentLine_fileTypeExclude = ['help', 'markdown', 'tex', 'fern', 'text']
  let g:indentLine_conceallevel = 2
  autocmd Filetype tex setlocal conceallevel=0
  let g:tex_conceal=''
'''

[[plugins]]
repo = 'nvim-lua/popup.nvim'

[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugings]]
repo = 'junegunn/vim-easy-align'
hook_add='''
  xmap ga <Plug>(EasyAlign)
  nmap ga <Plug>(EasyAlign)
'''
# [[plugins]]
# repo = 'nvim-telescope/telescope.nvim'
# hook_add='''
#   " Find files using Telescope command-line sugar.
#   nnoremap <leader>ff <cmd>Telescope find_files<cr>
#   nnoremap <leader>fg <cmd>Telescope live_grep<cr>
#   nnoremap <leader>fb <cmd>Telescope buffers<cr>
#   nnoremap <leader>fh <cmd>Telescope help_tags<cr>
# '''
